# Generated by Django 4.1.6 on 2023-02-13 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epicappAPI', '0005_alter_post_visibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='published',
        ),
        migrations.AddField(
            model_name='comment',
            name='contentType',
            field=models.CharField(choices=[('text/markdown', 'Textmarkdown'), ('text/plain', 'Textplain'), ('application/base64', 'Appimg'), ('image/png;base64', 'Pngimg'), ('image/jpeg;base64', 'Jpegimg')], default='text/plain', max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default='9befaaae-74aa-4a52-bd04-473ff74305a4', on_delete=django.db.models.deletion.CASCADE, to='epicappAPI.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=500),
        ),
    ]
